version: "3" 
services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terraform
    networks:
      - tfnet
    stdin_open: true
    tty: true
    #    environment:
    #      - AWS_ACCESS_KEY_ID
    #      - AWS_SECRET_ACCESS_KEY
    #      - AWS_DEFAULT_REGION
    env_file:
      - ./aws.env
    entrypoint: /bin/bash

networks:
  tfnet:
    driver: bridge
