name: Destroy terraform backend and save its state to s3

on:
  push:
    tags:
      - "destroy**"
      - "delete**"

jobs:
  # runs only when backend is not working/present
  test_destroys_locally_before_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Destroy backend terraform image and test aws terraform s3 backend existence
        run: |
          echo $AWS_REGION
          docker build -t terraform_backend \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
            --build-arg MODULE=backend terraform
          echo "The backend will be deleted from aws"
          docker run -t \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            terraform_backend destroy -auto-approve -input=false -json
          docker build -t terraform_infrastructure \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
            --build-arg MODULE=infrastructure terraform
          echo "The infrastructure will be deleted from aws"
          docker run -t \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            terraform_infrastructure destroy -auto-approve -input=false -json
          docker build -t terraform_lambda \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
            --build-arg MODULE=lambda terraform
          echo "The lambda will be deleted from aws"
          docker run -t \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            terraform_lambda destroy -auto-approve -input=false -json

