name: Test image of terraform backend and existence of backend

on: push

jobs:
  test_builds_locally_before_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend terraform image and test aws terraform s3 backend existence
        run: |
          docker build -t terraform_backend \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
            --build-arg MODULE=backend terraform
          docker run -t \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            --entrypoint /bin/cat \
            terraform_backend main.tf
