name: Test image of terraform backend and existence of backend

on: push

jobs:
  test_builds_locally_before_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build backend terraform image and test aws terraform s3 backend existence
        run: |
          docker build -t terraform_backend --build-arg MODULE=backend terraform
          docker run -t --rm --name terraform-local --entrypoint /bin/cat terraform_backend main.tf
