name: Test images locally

on: push

jobs:

  test-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and test lambda Docker image locally
        run: |
          docker build . --file lambda.Dockerfile --tag lambda-local:test
          docker run -d --name lambda-local -p 9000:8080 lambda-local:test
          docker ps -a
          sleep 5
          curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"Records":["s3": {"bucket": {"name":"bucket-powerex-files-input"}, "object": {"key": "testfile"}}]}'
          docker ps -a
          docker logs lambda-local

      - name: Build and test terraform Docker image locally
        run: |
          docker build -t tf-deploy -f Dockerfile .
          docker run -d --name terraform-local --entrypoint /bin/cat tf-deploy main.tf
